CREATE TABLE IF NOT EXISTS users (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           login VARCHAR(255) NOT NULL UNIQUE,
                           name VARCHAR(255) NOT NULL,
                           password VARCHAR(255) NOT NULL
);