CREATE TABLE auto_user (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           login VARCHAR(255) NOT NULL UNIQUE,
                           password VARCHAR(255) NOT NULL
);