CREATE TABLE posts (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           status VARCHAR(6),
                           description VARCHAR(255),
                           created_at TIMESTAMP NOT NULL,
                           price DECIMAL(10, 2) NOT NULL,
                           car_id BIGINT NOT NULL,
                           user_id BIGINT NOT NULL,
                           CONSTRAINT fk_post_car FOREIGN KEY (car_id)
                               REFERENCES cars(id) ON DELETE SET NULL,
                           CONSTRAINT fk_post_user FOREIGN KEY (user_id)
                               REFERENCES users(id) ON DELETE CASCADE

);