CREATE TABLE IF NOT EXISTS post_photos (
       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       post_id BIGINT NOT NULL,
       photo_path VARCHAR(255) NOT NULL,

        CONSTRAINT fk_photo_post_id
        FOREIGN KEY (post_id)
        REFERENCES posts(id)
        ON DELETE CASCADE
);