CREATE TABLE fuel_types (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            car_id VARCHAR(255) NOT NULL,
                            fuel_type_id VARCHAR(255) NOT NULL,
                            CONSTRAINT fk_car FOREIGN KEY (car_id)
                                REFERENCES cars(id) ON DELETE SET NULL,
                            CONSTRAINT fk_fuel_type FOREIGN KEY (fuel_type_id)
                                REFERENCES fuel_types(id) ON DELETE CASCADE
);