CREATE TABLE cars (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    vin VARCHAR(17) NOT NULL,
                    mileage BIGINT NOT NULL,
                    year_of_manufacture BIGINT NOT NULL,
                    count_owners BIGINT DEFAULT 0,
                    model_id BIGINT NOT NULL,
                    brand_id BIGINT NOT NULL,
                    category_id BIGINT NOT NULL,
                    body_id BIGINT NOT NULL,
                    engine_id BIGINT NOT NULL,
                    transmission_type_id BIGINT NOT NULL,
                    drive_type_id BIGINT NOT NULL,
                    wheel_side_id BIGINT NOT NULL,
                    car_color_id BIGINT NOT NULL,
                    CONSTRAINT fk_car_color_id FOREIGN KEY (car_color_id)
                        REFERENCES car_colors(id) ON DELETE RESTRICT,
                    CONSTRAINT fk_wheel_side_id FOREIGN KEY (wheel_side_id)
                        REFERENCES wheel_sides(id) ON DELETE RESTRICT,
                    CONSTRAINT fk_drive_type_id FOREIGN KEY (drive_type_id)
                        REFERENCES drive_types(id) ON DELETE RESTRICT,
                    CONSTRAINT fk_transmission_type_id FOREIGN KEY (transmission_type_id)
                        REFERENCES transmission_types(id) ON DELETE RESTRICT,
                    CONSTRAINT fk_engine_id FOREIGN KEY (engine_id)
                        REFERENCES engines(id) ON DELETE RESTRICT,
                    CONSTRAINT fk_body_id FOREIGN KEY (body_id)
                        REFERENCES bodies(id) ON DELETE RESTRICT,
                    CONSTRAINT fk_category_id FOREIGN KEY (category_id)
                        REFERENCES categories(id) ON DELETE RESTRICT,
                    CONSTRAINT fk_brand_id FOREIGN KEY (brand_id)
                        REFERENCES brands(id) ON DELETE RESTRICT,
                    CONSTRAINT fk_model_id FOREIGN KEY (model_id)
                        REFERENCES models(id) ON DELETE RESTRICT

);